# Plugin Created By JAhimaz | ItsJustDsAW

############################################################
# +------------------------------------------------------+ #
# |                  = EZ LINKS CONFIG =                 | #
# |                     VERSION 1.0.0                    | #
# +------------------------------------------------------+ #
############################################################

# Plugin Prefix
plugin-prefix: "&3[EZLinks]"

# The Title On The Top Of The Link Menu GUI
link-menu-title: "&3EzLinks &3Website Links"

# > Feel Free To Add More Link Sites (Maximum 53)
Links:
  Facebook:
    LinkURL: "https://www.facebook.com/"
    DisplayItem: "DIAMOND"
  Discord:
    LinkURL: "https://discord.gg/EAcPrQV"
    DisplayItem: "EMERALD"